/**
 * What this could become, written down so it can be voted on rather than
 * argued about at midnight.
 *
 * `state` is honest and is shown as such: 'live' works now, 'ready' is built
 * and waiting on something outside the repo, 'idea' is not built at all. Nothing
 * here is allowed to claim it works when it does not — that is the same rule
 * the customer-facing copy lives by.
 */
export const PHASES = [
  {
    id: 'now',
    title: 'Working now',
    blurb: 'Everything below is live on this app today.',
    items: [
      { key: 'status-link', name: 'One link per job', state: 'live',
        what: 'Booked in, on my way, on site, done. No promised time.' },
      { key: 'one-tap-text', name: 'Text or WhatsApp in one tap', state: 'live',
        what: 'Opens Messages or WhatsApp with the number and the message already written.' },
      { key: 'passkey', name: 'Face ID sign-in', state: 'live',
        what: 'No password to type in a van.' },
      { key: 'window-agree', name: 'Agree the window, do not announce it', state: 'live',
        what: 'Offer hours; they say that suits or ask for different ones and why. Either end can start it, and only an agreed window is stated as a fact.' },
      { key: 'window', name: 'Arrival window you can narrow', state: 'live',
        what: 'Sometime Tuesday becomes between 2 and 4 as the day settles.' },
      { key: 'run-position', name: 'Where they are in the day', state: 'live',
        what: 'You are 2nd today. A fact about order, not a clock.' },
      { key: 'presence', name: 'Will someone be in?', state: 'live',
        what: 'Four taps back from the customer. Saves the wasted trip.' },
      { key: 'answers-private', name: 'What you tell them stays between you', state: 'live',
        what: 'Your answers about the door, the dog and whether anyone is in go to the trade only. A forwarded link cannot read them back.' },
      { key: 'access-notes', name: 'Which door, the dog, what3words', state: 'live',
        what: 'Told once by the customer, read before you knock.' },
      { key: 'navigate', name: 'Navigate to the job', state: 'live',
        what: 'One tap opens directions in Maps — to the pin if there is one, the address if not.' },
      { key: 'one-tap-pin', name: 'Drop a pin with one tap', state: 'live',
        what: 'Standing at the door, one tap instead of pasting a Maps link. Either end can do it, and Navigate then runs to the exact spot.' },
      { key: 'map-links', name: 'what3words and dropped pins that open', state: 'live',
        what: 'Tap the three words or the pin and the right app opens on the right square.' },
      { key: 'door-photos', name: 'Photos of the house and the door', state: 'live',
        what: 'Set on the first visit so the next one is easy. Both sides see them.' },
      { key: 'brand-logo', name: 'Your logo on the page', state: 'live',
        what: 'Set once in Who to expect. The wallet card carries it too once Apple signs it.' },
      { key: 'who-to-expect', name: 'Who is coming and what they drive', state: 'live',
        what: 'Name, photo and the plate, shown only once you set off.' },
      { key: 'calendar', name: 'Put it in my calendar', state: 'live',
        what: 'Apple and Google. All day, or the window if you have set one.' },
      { key: 'installable', name: 'Add to home screen', state: 'live',
        what: 'Opens like an app, no address bar.' },
    ],
  },
  {
    id: 'next',
    title: 'Built, waiting on someone else',
    blurb: 'The code is done. These need an account or a certificate that only you can get.',
    items: [
      { key: 'push', name: 'Your phone buzzes when they set off', state: 'ready',
        what: 'Set off, arrived, done — on the lock screen, no app. The closest thing to the wallet card, and it costs nothing.',
        needs: 'One database migration and a key pair — both in setup.sh' },
      { key: 'wallet-pass', name: 'The card in Apple Wallet', state: 'ready',
        what: 'Updates itself on the lock screen when you tap a stage.',
        needs: 'Apple Developer Program, £79/yr' },
      { key: 'dvla', name: 'Van details from the number plate', state: 'ready',
        what: 'Type the plate and the make, model and colour fill themselves in, from the DVSA MOT history record. DVLA is the fallback and has no model.',
        needs: 'A free DVSA MOT history API key — applied for 2 Oct 2026, up to five working days' },
      { key: 'google-wallet', name: 'The same card on Android', state: 'idea',
        what: 'Google Wallet pass alongside the Apple one.',
        needs: 'Google Wallet issuer account, free' },
    ],
  },
  {
    id: 'soon',
    title: 'Next, if they are worth it',
    blurb: 'Tell me which of these you would actually use. That is what gets built.',
    items: [
      { key: 'sm8-sync', name: 'ServiceM8 follows the job', state: 'ready',
        what: 'Add a job by its ServiceM8 number and the card follows it: check in and the customer sees On site, complete it and they see Job done. Every event is checked against the job itself, never trusted.',
        needs: 'Your ServiceM8 API key — one command, scripts/connect-servicem8.sh' },
      { key: 'running-late', name: 'Running late, one tap', state: 'idea',
        what: 'Pushes the window back and tells them. Kills the "where are you" call.' },
      { key: 'photos', name: 'Photos when the job is done', state: 'idea',
        what: 'They see the finished work. Also your evidence if anyone queries it.' },
      { key: 'review-ask', name: 'Ask for the review at the right moment', state: 'idea',
        what: 'The page is open and the job just went well. Cheapest review you will get.' },
      { key: 'whatsapp-auto', name: 'Automatic WhatsApp updates', state: 'idea',
        what: 'The server messages them itself when you tap a stage. Needs the WhatsApp Business API and template approval.' },
      { key: 'live-location', name: 'Live location while you are driving', state: 'idea',
        what: 'Starts at On my way, stops dead at On site. No history kept.' },
      { key: 'customer-camera', name: 'Customer takes the door photo themselves', state: 'idea',
        what: 'A camera button on their page. Needs photo storage — an unsigned Cloudinary preset is a five-minute job.' },
      { key: 'branded-card', name: 'Your own logo on the wallet card', state: 'idea',
        what: 'The paid tier. Free shows TurnUp instead.' },
    ],
  },
  {
    id: 'later',
    title: 'The bigger idea',
    blurb: 'A different product, and the one this was always pointing at. Every item here needs the data model rebuilt around a journey with two ends.',
    items: [
      { key: 'access-trust', name: 'Do we know them well enough to let them in?', state: 'idea',
        what: 'When nobody will be in: let them in themselves via a key safe, leave it somewhere safe, or neither. Decided per trade per household, not per job, and the answer is remembered.' },
      { key: 'whereabouts-privacy', name: 'Who is allowed to ask if you are in', state: 'idea',
        what: 'Answering "will someone be in?" tells somebody a house is empty. A request from a name the household does not recognise should not get that answer at all.' },
      { key: 'two-roles', name: 'Anyone can be either end', state: 'idea',
        what: 'Today the trade always moves and the customer always waits. In fact one person MOVES and one WAITS, and either of you can be either — a mate dropping something off, a neighbour picking up a key.' },
      { key: 'pickup-dropoff', name: 'Pickup and drop-off are two journeys', state: 'idea',
        what: 'Returning a parcel is a courier coming TO you, then going to the depot. A removal is a pickup here, a drop-off there. Each end is its own “will someone be in?”' },
      { key: 'household', name: 'An account per address, not per job', state: 'idea',
        what: 'Two or three adults who can let someone in or sign for something. The address answers, not one phone.' },
      { key: 'couriers', name: 'Couriers use it too', state: 'idea',
        what: 'Same question, same answer, same two ends. A failed delivery costs them more than a wasted visit costs you.' },
      { key: 'customer-invite', name: 'The waiting end asks for it', state: 'idea',
        what: 'A customer sends a link to whoever is coming. That is how it stops being one plumber and becomes a standard.' },
      { key: 'big-jobs', name: 'Programme of works for a big job', state: 'idea',
        what: 'RIBA stages, variations, what has been signed off and by whom.' },
      { key: 'process-templates', name: 'The industry\u2019s own stage names on the card', state: 'idea',
        what: 'Every regulated trade already agreed what its stages are called: RIBA Plan of Work 0\u20137, building control inspections, PAS 2035 retrofit, the Conveyancing Protocol A\u2013F. Pick a template and the card speaks that language. See docs/research/formal-processes.md.' },
      { key: 'auto-stage', name: 'The card moves itself', state: 'ready',
        what: 'ServiceM8 check-in is On site and completion is Job done, by webhook and by pull-on-read, with nobody tapping anything. The first connector; others follow the same shape.',
        needs: 'The ServiceM8 key above' },
      { key: 'home-record', name: 'A record of your home', state: 'idea',
        what: 'Everything done to the house, by whom and when, with the certificate and the photos \u2014 kept with the address, not lost in an inbox or on a paper invoice. The next trade reads it before they arrive.' },
      { key: 'job-management', name: 'From tracker to the job itself', state: 'idea',
        what: 'The quote they accepted, the day it was done, the bill, the next service due. The link grows into the job, so a one-van firm runs the whole thing from the same place the customer already looks.' },
      { key: 'carplay', name: 'From the dash, not the phone', state: 'idea',
        what: 'The four stage buttons on the car’s own screen — CarPlay and Android Auto — or said to Siri or Google. Eyes on the road, hands on the wheel, the card still moves.' },
      { key: 'quoting', name: 'Quotes and invoices', state: 'idea',
        what: 'Only worth doing once the card is in a hundred wallets.' },
    ],
  },
]

export const STATE = {
  live:  { label: 'Live',        tone: 'done' },
  ready: { label: 'Ready',       tone: 'onsite' },
  idea:  { label: 'Not built',   tone: 'booked' },
}

export const ALL_ITEMS = PHASES.flatMap((p) => p.items)
